# Generated by Django 3.2.7 on 2021-09-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Paid")], default=1
                    ),
                ),
                (
                    "therapy_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapy.therapyslot",
                    ),
                ),
            ],
        ),
    ]
