# Generated by Django 3.2.7 on 2021-09-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("contact", models.CharField(max_length=15)),
                ("OT", models.BooleanField(default=False)),
                ("PT", models.BooleanField(default=False)),
                ("ST", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TherapyCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
                ("phone_no", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TherapySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "therapy_type",
                    models.CharField(
                        choices=[(1, "OT"), (2, "PT"), (3, "ST")], max_length=2
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapy.therapist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapy.therapist",
                    ),
                ),
                (
                    "therapy_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapy.therapycenter",
                    ),
                ),
            ],
        ),
    ]
