# Generated by Django 3.2.7 on 2021-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="OT",
            field=models.CharField(choices=[(1, "Yes"), (2, "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="PT",
            field=models.CharField(choices=[(1, "Yes"), (2, "No")], max_length=3),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="ST",
            field=models.CharField(choices=[(1, "Yes"), (2, "No")], max_length=3),
        ),
    ]
