# Generated by Django 3.2.7 on 2021-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0002_auto_20210918_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="OT",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="PT",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="ST",
            field=models.IntegerField(choices=[(1, "Yes"), (2, "No")]),
        ),
        migrations.AlterField(
            model_name="therapistschedule",
            name="day",
            field=models.IntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="therapyslot",
            name="therapy_type",
            field=models.IntegerField(choices=[(1, "OT"), (2, "PT"), (3, "ST")]),
        ),
    ]
