# Generated by Django 3.2.7 on 2021-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0004_alter_therapyslot_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyslot",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Available"), (2, "Booked")], default=1
            ),
        ),
        migrations.AddField(
            model_name="therapyslot",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
