# Generated by Django 3.2.7 on 2021-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0005_auto_20210919_0232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapyslot",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
