# Generated by Django 3.2.7 on 2021-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0005_auto_20210919_0232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapyslot",
            name="therapy_type",
            field=models.IntegerField(
                blank=True, choices=[(1, "OT"), (2, "PT"), (3, "ST")], null=True
            ),
        ),
    ]
