# Generated by Django 3.2.7 on 2021-09-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0006_alter_therapyslot_therapy_type"),
        ("therapy", "0006_alter_therapyslot_title"),
    ]

    operations = []
