"""init

Revision ID: 07b0b89eaf2c
Revises: 9c68efbf5703
Create Date: 2021-09-18 15:43:41.076389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07b0b89eaf2c"
down_revision = "9c68efbf5703"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
