"""init

Revision ID: 8f03a8238bb8
Revises: 07b0b89eaf2c
Create Date: 2021-09-18 15:51:08.245807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f03a8238bb8"
down_revision = "07b0b89eaf2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("contact_num", sa.String(length=15), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("father_name", sa.String(length=100), nullable=False),
        sa.Column("mother_name", sa.String(length=100), nullable=False),
        sa.Column("father_occupation", sa.String(length=50), nullable=False),
        sa.Column("mother_occupation", sa.String(length=50), nullable=False),
        sa.Column("father_contact_num", sa.String(length=15), nullable=False),
        sa.Column("mother_contact_num", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "therapist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("contact_num", sa.String(length=15), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_aid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("family_income", sa.Integer(), nullable=False),
        sa.Column("expenses", sa.Integer(), nullable=False),
        sa.Column("eligible_for_aid", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "special_child",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "appointment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("appointment_datetime", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["special_child.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["therapist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "waitlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("therapist_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["special_child.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["therapist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waitlist")
    op.drop_table("appointment")
    op.drop_table("special_child")
    op.drop_table("financial_aid")
    op.drop_table("therapist")
    op.drop_table("family")
    op.drop_table("donor")
    # ### end Alembic commands ###
