"""account_tbl_added

Revision ID: a6d5be6e78e1
Revises: 4f4c2aa74b2f
Create Date: 2021-09-18 18:46:23.824141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6d5be6e78e1"
down_revision = "4f4c2aa74b2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
