"""back

Revision ID: acd3376ca02e
Revises: dfb0ec10054b
Create Date: 2021-09-19 10:21:15.592358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acd3376ca02e"
down_revision = "dfb0ec10054b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
