# Generated by Django 3.2.7 on 2021-09-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingListOT",
            fields=[
                (
                    "list_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="queues.list",
                    ),
                ),
            ],
            bases=("queues.list",),
        ),
        migrations.RemoveField(
            model_name="masterlist",
            name="id",
        ),
        migrations.RemoveField(
            model_name="waitinglistst",
            name="id",
        ),
        migrations.AddField(
            model_name="masterlist",
            name="list_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="queues.list",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waitinglistst",
            name="list_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="queues.list",
            ),
            preserve_default=False,
        ),
    ]
