# Generated by Django 3.2.7 on 2021-09-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0003_alter_list_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="remarks",
            field=models.TextField(null=True),
        ),
    ]
