# Generated by Django 3.2.7 on 2021-09-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0004_alter_list_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
