# Generated by Django 3.2.7 on 2021-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("father_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(blank=True, max_length=100)),
                ("cnic", models.CharField(blank=True, max_length=15)),
                ("contact", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "Eligible"), (2, "Enrolled"), (3, "UnEnrolled")],
                        default=3,
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
