# Generated by Django 3.2.7 on 2021-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Eligible"), (2, "Enrolled"), (3, "UnEnrolled")], default=3
            ),
        ),
    ]
