# Generated by Django 3.2.7 on 2021-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Ineligible"), (2, "Enrolled"), (3, "UnEnrolled")],
                default=3,
            ),
        ),
    ]
